### ISSUE TITLE
Why is the redact function of the Naive Signature empty?

### ISSUE THREAD

**Issue by ftmateus** [Romern/redactionschemes#3]
https://github.com/Romern/redactionschemes/blob/4428e3a30215b1d05f3d581a7d877a6d5f358e46/NaiveSignature.go#L97

**Comment by Romern** [comment]
You can use the original signature for redacted data, as it is not bound to a particular set of partitions. For the other methods, this is not the case. If you wanted to minimize the length of the signature, you could implement the redact function to let out the signatures for the redacted partitions.

**Comment by Romern** [comment]
Thinking about it it obviously is leaking the hash of the partition, so it should be implemented.

**Comment by Romern** [comment]
Implemented in https://github.com/Romern/redactionschemes/commit/aa4e3ac05d2a2486c563450bc8b72a43cfb8bb6b . I also fixed some other bugs
